# Generated by Django 6.1 on 2026-08-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True)),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True)),
                ('pickup_actual_at', models.DateTimeField(blank=True, null=True)),
                ('shipment_fee_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carrier_fault', models.BooleanField(default=False)),
                ('customer_fault', models.BooleanField(default=False)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.account')),
            ],
            options={
                'ordering': ['order_id'],
                'indexes': [models.Index(fields=['account', 'status'], name='orders_orde_account_611ca4_idx'), models.Index(fields=['carrier'], name='orders_orde_carrier_20570d_idx')],
            },
        ),
    ]
