# Generated by Django 6.1 on 2026-08-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AGENT_REQUEST', 'Agent Request'), ('TOOL_CALL', 'Tool Call'), ('TOOL_SUCCESS', 'Tool Success'), ('TOOL_FAILURE', 'Tool Failure'), ('SOURCE_CONFLICT', 'Source Conflict'), ('AUTHORIZATION_DENIED', 'Authorization Denied'), ('PENDING_ACTION_CREATED', 'Pending Action Created'), ('ACTION_CONFIRMED', 'Action Confirmed'), ('ACTION_EXECUTED', 'Action Executed'), ('ACTION_FAILED', 'Action Failed')], max_length=64)),
                ('tool_name', models.CharField(blank=True, max_length=128)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='agent.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
