# Generated by Django 6.1 on 2026-08-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='active', max_length=32)),
                ('csm', models.CharField(blank=True, max_length=255)),
                ('contract_file', models.CharField(blank=True, max_length=255)),
                ('premium_support', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
    ]
