# Generated by Django 6.1 on 2026-08-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('CUSTOMER_AGREEMENT', 'Customer Agreement'), ('POLICY_SOP', 'Policy / SOP'), ('PRODUCT_DOC', 'Product Documentation'), ('HISTORICAL_CONTEXT', 'Historical Tickets / Notes'), ('DEPRECATED', 'Deprecated')], max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CURRENT', 'Current'), ('DEPRECATED', 'Deprecated'), ('CONTEXT_ONLY', 'Context Only')], max_length=32)),
                ('authority_level', models.IntegerField(default=0)),
                ('scope_type', models.CharField(choices=[('CUSTOMER_SPECIFIC', 'Customer Specific'), ('GENERAL', 'General'), ('PRODUCT', 'Product / Domain')], default='GENERAL', max_length=32)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('explicit_override_domains', models.JSONField(blank=True, default=list)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.account')),
                ('supersedes_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['-authority_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('page_reference', models.CharField(blank=True, max_length=64)),
                ('chunk_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('MONITORING', 'Monitoring'), ('INVESTIGATING', 'Investigating'), ('HISTORICAL', 'Historical')], default='ACTIVE', max_length=32)),
                ('known_issue_status', models.CharField(blank=True, max_length=32)),
                ('known_issue_id', models.CharField(blank=True, max_length=64)),
                ('domain', models.CharField(blank=True, max_length=128)),
                ('chunk_effective_date', models.DateField(blank=True, null=True)),
                ('chunk_expiry_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
