# Generated by Django 6.1 on 2026-08-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('subject', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=64)),
                ('assigned_to', models.CharField(blank=True, max_length=128)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('historical_resolution', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=8)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='tickets_tic_account_d2ddd7_idx'), models.Index(fields=['severity'], name='tickets_tic_severit_e9e7a9_idx'), models.Index(fields=['category'], name='tickets_tic_categor_fc7dd1_idx')],
            },
        ),
    ]
